namespace Nexus.Common.Enum
{
	public enum RoleDefinitionEnum
	{
	    None = 1,
	    ViewMenuOrder = 2,
	    ViewListPendingOrder = 3,
	    ApprovalPendingOrder = 4,
	    DeletePendingOrder = 5,
	    RejectPendingOrder = 6,
	    ViewListOrder = 7,
	    CreateOrder = 8,
	    UpdateOrder = 9,
	    DeleteOrder = 10,
	    ViewMenuProduct = 11,
	    ViewListProduct = 12,
	    CreateProduct = 13,
	    UpdateProduc = 14,
	    DeleteProduct = 15,
	    ViewListProductType = 16,
	    CreateProductType = 17,
	    UpdateProductType = 18,
	    DeleteProductType = 19,
	    ViewListImportReceipt = 20,
	    CreateImportReceipt = 21,
	    ViewListProvider = 22,
	    CreateProvider = 23,
	    UpdateProvider = 24,
	    DeleteProvider = 25,
	    ViewListCustomer = 26,
	    CreateCustomer = 27,
	    UpdateCustomer = 28,
	    DeleteCustomer = 29,
	    ViewListPost = 30,
	    CreatePost = 31,
	    UpdatePost = 32,
	    DeletePost = 33,
	    ViewListRole = 34,
	    CreateRole = 35,
	    UpdateRole = 36,
	    DeleteRole = 37,
	    AddOrDeletePermisionToRole = 38,
	    ViewListUser = 39,
	    CreateUser = 40,
	    UpdateUser = 41,
	    AssignRoleForUser = 42,
	    DeleteUser = 43,
	    ViewListPermission = 44,
	    ViewMenuConfig = 45,
	    ViewListManufacturer = 46,
	    CreateManufacturer = 47,
    }
}

