//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonicationMemory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonicationMemory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;configuration&gt;
        ///	&lt;appSettings&gt;
        ///		&lt;add key=&quot;Main.ConnectionString&quot; value=&quot;$CONNECTION_STRING$&quot; /&gt;
        ///	&lt;/appSettings&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;$PROJECT_NAMESPACE$.BusinessLayer&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;iqbal&quot;)]
        ///[assembly: AssemblyProduct(&quot;$PROJECT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.ComponentModel;
        ///
        ///namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer
        ///{
        ///    /// &lt;summary&gt;
        ///    /// base class for all business objects
        ///    /// &lt;/summary&gt;
        ///    public abstract class BusinessObjectBase : INotifyPropertyChanged
        ///    {
        ///
        ///        #region Data Member
        ///
        ///        bool _disablePropertyChangeEvent = false;
        ///        Validation.ValidationRules _validationRules = null;
        ///
        ///        #endregion
        ///
        ///        #region Properties
        ///
        ///        #region Internal Properties
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Business_BusinessObjectBase {
            get {
                return ResourceManager.GetString("Business_BusinessObjectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using $PROJECT_NAMESPACE$.BusinessLayer.DataLayer;
        ///
        ///namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer
        ///{
        ///    public class $CLASS_NAME$Factory
        ///    {
        ///
        ///        #region data Members
        ///
        ///        $CLASS_NAME$Sql _dataObject = null;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        public $CLASS_NAME$Factory()
        ///        {
        ///            _dataObject = new $CLASS_NAME$Sql();
        ///        }
        ///
        ///        #endregion
        ///
        ///
        ///        #region Public Meth [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Business_BusinessObjectFactory {
            get {
                return ResourceManager.GetString("Business_BusinessObjectFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Class to create custom exception
        ///    /// &lt;/summary&gt;
        ///    public class InvalidBusinessObjectException: Exception
        ///    {
        ///
        ///        #region Data members
        ///
        ///        string _methodName = string.Empty;
        ///
        ///        #endregion 
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor to set message
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;message&quot;&gt;error messa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Business_InvalidBusinessObjectException {
            get {
                return ResourceManager.GetString("Business_InvalidBusinessObjectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.50727&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{C6FD9F84-A18E-472D-BA4B-7ED274F5B276}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Business_ProdjectFile {
            get {
                return ResourceManager.GetString("Business_ProdjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Data.SqlClient;
        ///
        ///namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.DataLayer
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Data layer base class for database interaction.
        ///    /// &lt;/summary&gt;
        ///    abstract class DataLayerBase : IDisposable
        ///    {
        ///        #region Data Members
        ///
        ///        SqlConnection _mainConnection;        
        ///        bool _isDisposed;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor 
        ///        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataLayer_DataLayerBase {
            get {
                return ResourceManager.GetString("DataLayer_DataLayerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using Oracle.ManagedDataAccess.Client;
        ///using QuantEdge.Entity;
        ///using QuantEdge.Entity.Entities;
        ///using QuantEdge.Worker.Common.DatabaseDAL.Common;
        ///using System.Data;
        ///
        ///namespace QuantEdge.Worker.Common.DatabaseDAL.EntitySql
        ///{
        ///	public class $CLASS_NAME$Sql : EntityBaseSql 
        ///	{
        ///
        ///        #region Constructor
        ///
        ///		public $CLASS_NAME$Sql()
        ///		{
        ///			 Init();
        ///		}
        ///
        ///        #endregion
        ///		
        ///		#region Init
        ///
        ///		private void Init()
        ///		{
        ///           Insertsql = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataLayer_EntitySql {
            get {
                return ResourceManager.GetString("DataLayer_EntitySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Data.SqlClient;
        ///
        ///namespace CommonicationMemory.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Data layer base class for database interaction.
        ///    /// &lt;/summary&gt;
        ///    public abstract class DataLayerBase : IDisposable
        ///    {
        ///        #region Data Members
        ///
        ///        SqlConnection _mainConnection;        
        ///        bool _isDisposed;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor 
        ///        /// &lt;/summary&gt;
        ///        public DataLayerBase [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataLayerBase {
            get {
                return ResourceManager.GetString("DataLayerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DbInfo {
            get {
                object obj = ResourceManager.GetObject("DbInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///
        ///namespace CommonicationMemory.Resources
        ///{
        ///    public abstract class EntityBaseSql
        ///    {
        ///        public string Insertsql = &quot;&quot;;
        ///        public string Updatesql = &quot;&quot;;
        ///        public string Deletesql = &quot;&quot;;
        ///        public string Selectsql = &quot;&quot;;
        ///        public CommandType CommandTypeProcedure = CommandType.StoredProcedure;
        ///        public CommandType CommandTypeText = CommandType.Text;
        ///        /// &lt;summary&gt;
        ///        // [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityBaseSql {
            get {
                return ResourceManager.GetString("EntityBaseSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CommonicationMemory.Resources
        ///{
        ///    public class EntityManager
        ///    {
        ///        #region Instance
        ///
        ///        public static EntityManager Instance
        ///        {
        ///            get { return Nested.Instance; }
        ///        }
        ///
        ///        private class Nested
        ///        {
        ///            internal static readonly EntityManager Instance = new EntityManager();
        ///        }
        ///
        ///        #endregion
        ///
        ///        public EntityBaseSql GetMyEntity(string entityName)
        ///        {
        ///
        ///            if (entityName.Equals(MemberInfo.ENTITY_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityManager {
            get {
                return ResourceManager.GetString("EntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // IMPORTANT: THIS IS MACHINE-GENERATED CODE
        ///// PLEASE DO NOT EDIT
        ///// Generated by Stateless Designer
        ///// http://statelessdesigner.codeplex.com/
        ///
        ///using Stateless;
        ///
        ///namespace QuantEdge.Worker.DataProviderManager.Processor.GetList%EntityName%Request
        ///{
        ///  public class Flow_GetList%EntityName%Request
        ///  {
        ///    public delegate void UnhandledTriggerDelegate(State state, Trigger trigger);
        ///    public delegate void EntryExitDelegate();
        ///    public delegate bool GuardClauseDelegate();
        ///
        ///    public enum Trigg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // IMPORTANT: THIS IS MACHINE-GENERATED CODE
        ///// PLEASE DO NOT EDIT
        ///// Generated by Stateless Designer
        ///// http://statelessdesigner.codeplex.com/
        ///
        ///using Stateless;
        ///
        ///namespace QuantEdge.Worker.RiskManager.Processor.Update%EntityName%Request
        ///{
        ///  public class Flow_Update%EntityName%Request
        ///  {
        ///    public delegate void UnhandledTriggerDelegate(State state, Trigger trigger);
        ///    public delegate void EntryExitDelegate();
        ///    public delegate bool GuardClauseDelegate();
        ///
        ///    public enum Trigger
        ///    {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlowUpdate {
            get {
                return ResourceManager.GetString("FlowUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace QuantEdge.Entity.Keys
        ///{
        ///    public class %EntityName%Keys
        ///    {
        ///        #region Properties
        ///
        ///        %KeysProperties%
        ///
        ///        #endregion
        ///
        ///        public override int GetHashCode()
        ///        {
        ///            unchecked
        ///            {
        ///                %KeysHashCode%
        ///                return result;
        ///            }
        ///        }
        ///
        ///        public override bool Equals(object obj)
        ///        {
        ///            if (ob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using QuantEdge.Entity.Entities;
        ///using QuantEdge.Message.Common;
        ///using QuantEdge.Message.Response.DataProvider;
        ///using QuantEdge.Message.Topic;
        ///using Anotar.Log4Net;
        ///using System.Linq;
        ///using QuantEdge.Common.Enum;
        ///using QuantEdge.Entity;
        ///using QuantEdge.Worker.DataProviderManager.ReaderDatabase;
        ///
        ///namespace QuantEdge.Worker.DataProviderManager.Processor.GetList%EntityName%Request
        ///{
        ///    public class Process_GetList%EntityName%Request : IDisposable
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///using System;
        ///using System.Linq;
        ///using Anotar.Log4Net;
        ///using Language.Languages;
        ///using QuantEdge.Common.Enum;
        ///using QuantEdge.Entity;
        ///using QuantEdge.Entity.Entities;
        ///using QuantEdge.Lib.Broadcast;
        ///using QuantEdge.Lib.Memory;
        ///using QuantEdge.Message.Common;
        ///using QuantEdge.Message.Memory;
        ///using QuantEdge.Message.Response.Risk;
        ///using QuantEdge.Message.Topic;
        ///using QuantEdge.Worker.RiskManager.Utils;
        ///
        ///namespace QuantEdge.Worker.RiskManager.Processor.Update%EntityName%Request
        ///{
        ///    public cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessUpdate {
            get {
                return ResourceManager.GetString("ProcessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--  
        ///Stateless Designer statemachine.
        ///For more information: http://statelessdesigner.codeplex.com/
        ///--&gt;
        ///&lt;statemachine xmlns=&quot;http://statelessdesigner.codeplex.com/Schema&quot;&gt;
        ///  &lt;settings&gt;
        ///    &lt;itemname&gt;Flow_Update%EntityName%Request&lt;/itemname&gt;
        ///    &lt;namespace&gt;QuantEdge.Worker.RiskManager.Processor.Update%EntityName%Request&lt;/namespace&gt;
        ///    &lt;class&gt;public&lt;/class&gt;
        ///  &lt;/settings&gt;
        ///  &lt;triggers&gt;
        ///    &lt;trigger&gt;Next&lt;/trigger&gt;
        ///    &lt;trigger&gt;Error&lt;/trigger&gt;
        ///  &lt;/triggers&gt;
        ///  &lt;states&gt;
        ///    &lt;state start=&quot;yes&quot;&gt;Input [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SateUpdate {
            get {
                return ResourceManager.GetString("SateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Globalization;
        ///using System.IO;
        ///using System.Reflection;
        ///using System.Threading;
        ///using System.Xml;
        ///
        ///namespace CommonicationMemory.Resources
        ///{
        ///    public class ServerConfig
        ///    {
        ///        #region fields
        ///
        ///        public const string DEFAULT_PATH = @&quot;C:\QuantEdge\&quot;;
        ///        private const string FILE_PATH = @&quot;\Config\ServerConfig.xml&quot;;
        ///        private const string DB_CONFIG_FILE = @&quot;DBConfig.xml&quot;;
        ///        private const string EXCHANGE_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServerConfig {
            get {
                return ResourceManager.GetString("ServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CommonicationMemory.Resources
        ///{
        ///    public class ServerInfo
        ///    {
        ///        private const string SERVER_NAME = &quot;Visiontriding Database&quot;;
        ///        private const string DB_CONFIG_DEFAULT =
        ///            &quot;Data Source=.;Initial Catalog=Exchange;User ID=lemon;Password=admin;Persist Security Info=True&quot;;
        ///
        ///        private readonly object _lock = new object();
        ///        private string _connectionString;
        ///
        ///        public ServerInfo()
        ///        {
        ///            _connectionString = string.Empty;
        ///        }
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServerInfo {
            get {
                return ResourceManager.GetString("ServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--  
        ///Stateless Designer statemachine.
        ///For more information: http://statelessdesigner.codeplex.com/
        ///--&gt;
        ///&lt;statemachine xmlns=&quot;http://statelessdesigner.codeplex.com/Schema&quot;&gt;
        ///  &lt;settings&gt;
        ///    &lt;itemname&gt;Flow_GetList%EntityName%Request&lt;/itemname&gt;
        ///    &lt;namespace&gt;QuantEdge.Worker.DataProviderManager.Processor.GetList%EntityName%Request&lt;/namespace&gt;
        ///    &lt;class&gt;public&lt;/class&gt;
        ///  &lt;/settings&gt;
        /// &lt;triggers&gt;     
        ///    &lt;trigger&gt;Next&lt;/trigger&gt;
        ///  &lt;/triggers&gt;
        ///  &lt;states&gt;     
        ///    	&lt;state start=&quot;yes&quot;&gt;ListRequest&lt;/st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stateless {
            get {
                return ResourceManager.GetString("Stateless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace CommonicationMemory.Resources
        ///{
        ///    public class UpdateEntityDao
        ///    {
        ///        #region Data Members
        ///
        ///        private readonly UpdateEntitySql _dataObject;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        public UpdateEntityDao()
        ///        {
        ///            _dataObject = new UpdateEntitySql();
        ///        }
        ///
        ///        #endregion
        ///
        ///        #region Public Methods
        ///
        ///
        ///        /// &lt;summary&gt;
        ///        /// 
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateEntityDAO {
            get {
                return ResourceManager.GetString("UpdateEntityDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///
        ///namespace CommonicationMemory.Resources
        ///{
        ///    public class UpdateEntitySql : DataLayerBase
        ///    {
        ///        public bool Update(List&lt;EntityCommand&gt; listEntityActionCommand)
        ///        {
        ///            int commandindex = 0;
        ///            if (MainConnection.State == ConnectionState.Closed)
        ///                MainConnection.Open();
        ///            var transaction = MainConnection.BeginTransaction();
        ///            var com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateEntitySql {
            get {
                return ResourceManager.GetString("UpdateEntitySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Broken rules
        ///    /// &lt;/summary&gt;
        ///    public class BrokenRule
        ///    {
        ///
        ///        #region Data Members
        ///
        ///        string _ruleName = string.Empty;
        ///        string _description = string.Empty;
        ///        string _propertyName = string.Empty;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// constructor to get rule information
        ///        /// &lt;/summary&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_BrokenRule {
            get {
                return ResourceManager.GetString("Validation_BrokenRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Class to containt the list of the broken rules
        ///    /// &lt;/summary&gt;
        ///    public class BrokenRulesList : List&lt;BrokenRule&gt;
        ///    {
        ///        #region Internal Methods
        ///
        ///        /// &lt;summary&gt;
        ///        /// Add broken rule into the list
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;rule&quot;&gt;rule&lt;/param&gt;
        ///        internal void  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_BrokenRulesList {
            get {
                return ResourceManager.GetString("Validation_BrokenRulesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Comparing for validation rules
        ///    /// &lt;/summary&gt;
        ///    public abstract class ValidateRuleBase
        ///    {
        ///        #region Data Members
        ///
        ///        string _propertyName = string.Empty;
        ///        string _friendlyName = string.Empty;
        ///        string _description = string.Empty;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Construcot 
        ///        /// &lt;/summ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleBase {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// validate Not null rule
        ///    /// &lt;/summary&gt;
        ///    class ValidateRuleNotNull : ValidateRuleBase
        ///    {
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;propertyName&quot;&gt;name of property&lt;/param&gt;
        ///        public ValidateRuleNotNull(string propertyName)
        ///            : this(propertyName, propertyName)
        ///        {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleNotNull {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Text.RegularExpressions;
        ///
        ///namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// validate using Regular expression
        ///    /// &lt;/summary&gt;
        ///    class ValidateRuleRegexMatching : ValidateRuleBase
        ///    {
        ///        #region Data Members
        ///
        ///        string _regexExpression = string.Empty;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleRegexMatching {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleRegexMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// validate the maximun length of the string
        ///    /// &lt;/summary&gt;
        ///    class ValidateRuleStringMaxLength : ValidateRuleBase
        ///    {
        ///
        ///        #region Data member
        ///
        ///        int _length = 0;
        ///
        ///        #endregion
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constrcutor
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;propertyName&quot;&gt;name of property&lt;/param&gt;
        ///        /// &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleStringMaxLength {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleStringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Validate the required value
        ///    /// &lt;/summary&gt;
        ///    class ValidateRuleStringRequired : ValidateRuleBase
        ///    {
        ///
        ///        #region Constructor
        ///
        ///        /// &lt;summary&gt;
        ///        /// Constructor
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;propertyName&quot;&gt;name of property&lt;/param&gt;
        ///        public ValidateRuleStringRequired(string propertyName)
        ///            : this(propertyName, propertyName) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidateRuleStringRequired {
            get {
                return ResourceManager.GetString("Validation_ValidateRuleStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Reflection;
        ///
        ///namespace CommonicationMemory.Resources
        ///
        ///$PROJECT_NAMESPACE$.BusinessLayer.Validation
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Class to contain the validation rules of the object
        ///    /// &lt;/summary&gt;
        ///    class ValidationRules
        ///    {
        ///
        ///        #region Data Members
        ///
        ///        BrokenRulesList _brokenRulesList = null;
        ///        Dictionary&lt;string, List&lt;ValidateRuleBase&gt;&gt; _validationRulesList = null;
        ///        object _parentObject = null;
        ///
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Validation_ValidationRules {
            get {
                return ResourceManager.GetString("Validation_ValidationRules", resourceCulture);
            }
        }
    }
}
